<?php print $this->getTitle(); ?> 
{{pdf_row_separator}}
<?php if ($this->getPaymentType()): ?>
  Payment Type: <?php print $this->getPaymentType(); ?>{{pdf_row_separator}}
<?php endif; ?>
<?php if ($this->getCcLast4()): ?>
  Last 4 Card Digits: <?php print $this->getCcLast4(); ?>{{pdf_row_separator}}
<?php endif; ?>
<?php if ($this->getTransactionReference()): ?>
  Transaction Reference: <?php print $this->getTransactionReference(); ?>{{pdf_row_separator}}
<?php endif; ?>
<?php if ($this->getAuthCode()): ?>
  Auth Code: <?php print $this->getAuthCode(); ?>{{pdf_row_separator}}
<?php endif; ?>
