<b><?php print $this->getTitle(); ?></b>
<br /><br />
<ul>
	<?php if ($this->getAccountTypeDescription()): ?>
    	<li>Account Type Description: <?php print $this->getAccountTypeDescription(); ?></li>
    <?php endif; ?>
    <?php if ($this->getTransactionReference()): ?>
    <li>Transaction Reference: <a href="<?php print $this->getTransactionReferenceUrl(); ?>"><?php print $this->getTransactionReference(); ?></a></li>
    <?php endif; ?>
    <?php if ($this->getSecurityAddress()): ?>
    <li>Security Response Address: <span style="<?php print $this->getSecurityAddressStyle(); ?>"><?php print $this->getSecurityAddress(); ?></span></li>
    <?php endif; ?>
    <?php if ($this->getSecurityPostcode()): ?>
    <li>Security Response Postcode: <span style="<?php print $this->getSecurityPostcodeStyle(); ?>"><?php print $this->getSecurityPostcode(); ?></span></li>
    <?php endif; ?>
    <?php if ($this->getSecurityCode()): ?>
    <li>Security Response Security Code: <span style="<?php print $this->getSecurityCodeStyle(); ?>"><?php print $this->getSecurityCode(); ?></span></li>
	<?php endif; ?>
	<?php if ($this->getFraudControlShieldStatusCode()): ?>
	<li>Fraud Control Shield Status Code: <span style="<?php print $this->getFraudControlShieldStatusCodeStyle(); ?>"><?php print $this->getFraudControlShieldStatusCode(); ?></span></li>
    <?php endif; ?>
    <?php if ($this->getEnrolled()): ?>
    <li>3D Enrolled: <?php print $this->getEnrolled(); ?></li>
    <?php endif; ?>
    <?php if ($this->getStatus()): ?>
    <li>3D Status: <?php print $this->getStatus(); ?></li>
    <?php endif; ?>
    <?php if ($this->getPaymentType()): ?>
    <li>Payment Type: <?php print $this->getPaymentType(); ?></li>
    <?php endif; ?>
    <?php if ($this->getCcLast4()): ?>
    <li>Last 4 Card Digits: <?php print $this->getCcLast4(); ?></li>
    <?php endif; ?>
</ul>
<?php if ($this->getTransactionReference()): ?>
	<a href="<?php print $this->getMystUrl(); ?>" target="_blank">View in MyST</a>
	<br /><br />
<?php endif; ?>