<?php $_code=$this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none">
  <li>
    <label for="<?php print $_code; ?>_transaction_reference">
    <?php print $this->getCardNumberLabel(); ?>
    </label>
  </li>
    <?php foreach($this->getSavedCards() as $card): ?>
      <li class="control">
        <input type="radio" name="payment[securetrading_stpp_reference_id]" id="<?php print $_code; ?>_reference_id_<?php print $card->getReferenceId(); ?>" value="<?php print $card->getReferenceId(); ?>" class="radio" />
        <label for="<?php print $_code; ?>_reference_id_<?php print $card->getReferenceId(); ?>">
    <?php print $this->getAgreementLabel($card); ?>
        </label>
      </li>
	<?php endforeach; ?>
</ul>