<?php $_code=$this->getMethodCode() ?>
<ul id="payment_form_<?php echo $_code ?>" style="display:none">
    <li>
        <label for="<?php print $_code; ?>_payment_type">
            <?php print $this->getCardTypeLabel(); ?>
            <em class="required">*</em>
        </label>
        <div class="input-box">
            <select name="payment[securetrading_stpp_payment_type]" id="<?php print $_code; ?>_payment_type" class="required-entry">
                <option value=""><?php print $this->__('Please select an option...'); ?></option>
                <?php foreach($this->getAcceptedCards() as $key => $value): ?>
                    <option value="<?php print $key; ?>"><?php print $value; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php print $_code; ?>_card_number">
            <?php print $this->getCardNumberLabel(); ?>
            <em class="required">*</em>
        </label>
        <div class="input-box">
            <input type="text" name="payment[securetrading_stpp_card_number]" id="<?php print $_code; ?>_card_number" class="required-entry" />
        </div>
    </li>
    <li>
        <label for="<?php print $_code; ?>_start_date_month">
            <?php print $this->getCardStartDateLabel(); ?>
       </label>
        <div class="input-box">
            <select name="payment[securetrading_stpp_start_date_month]" id="<?php print $_code; ?>_start_date_month" class="month">
             <?php foreach($this->getMonths() as $k => $v): ?>
                <option value="<?php print $k; ?>"><?php print $v; ?></option>
             <?php endforeach; ?>
            </select>
            <select name="payment[securetrading_stpp_start_date_year]" id="<?php print $_code; ?>_start_date_year" class="year">
                <?php foreach($this->getStartYears() as $year): ?>
                    <option value="<?php print $year; ?>"><?php print $year; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php print $_code; ?>_expiry_date_month">
            <?php print $this->getCardExpiryDateLabel(); ?>
            <em class="required">*</em>
        </label>
        <div class="input-box">
            <select name="payment[securetrading_stpp_expiry_date_month]" id="<?php print $_code; ?>_expiry_date_month" class="month required-entry">
                 <?php foreach($this->getMonths() as $k => $v): ?>
                    <option value="<?php print $k; ?>"><?php print $v; ?></option>
                 <?php endforeach; ?>
            </select>
            <select name="payment[securetrading_stpp_expiry_date_year]" id="<?php print $_code; ?>_expiry_date_year" class="year required-entry">
                <?php foreach($this->getExpiryYears() as $year): ?>
                    <option value="<?php print $year; ?>"><?php print $year; ?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </li>
    <li>
        <label for="<?php print $_code; ?>_security_code">
            <?php print $this->getCardSecurityCodeLabel(); ?>
            <em class=required">*</em>
        </label>
        <div class="input-box">
            <input type="text" name="payment[securetrading_stpp_security_code]" id="<?php print $_code; ?>_security_code" class="required-entry" maxlength="4" />
        </div>

        <label for="<?php print $_code; ?>_issue_number">
            <?php print $this->getCardIssueNumberLabel(); ?>
        </label>
        <div class="input-box">
            <input type="text" name="payment[securetrading_stpp_issue_number]" id="<?php print $_code; ?>_issue_number" />
        </div>
    </li>
</ul>