<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <span id="<?php print $_code; ?>_description"><?php print $this->getDescription(); ?></span>
        </li>
        <li>
            <label for="<?php print $_code; ?>_payment_type" class="required">
                <?php print $this->getCardTypeLabel(); ?>
                <em>*</em>
            </label>
            <div class="input-box">
                <select name="payment[securetrading_stpp_payment_type]" id="<?php print $_code; ?>_payment_type" class="required-entry">
                    <option value=""><?php print $this->__('Please select an option...'); ?></option>
                    <?php foreach($this->getAcceptedCards() as $key => $value): ?>
                        <option value="<?php print $key; ?>"><?php print $value; ?></option>
                    <?php endforeach; ?>
                </select>
                <?php //print $this->getCardTypeDescription(); ?>
            </div>
        </li>
        <li>
            <label for="<?php print $_code; ?>_card_number" class="required">
                <?php print $this->getCardNumberLabel(); ?>
                <em>*</em>
            </label>
            <div class="input-box">
                <input type="text" name="payment[securetrading_stpp_card_number]" id="<?php print $_code; ?>_card_number" class="required-entry" />
                <?php //print $this->getCardNumberDescription(); ?>
            </div>
        </li>
        <?php if ($this->canShowStartDate()): ?>
        <li>
            <label for="<?php print $_code; ?>_start_date_month">
                <?php print $this->getCardStartDateLabel(); ?>
           </label>
            <div class="input-box">
                <div class="v-fix">
                    <select name="payment[securetrading_stpp_start_date_month]" id="<?php print $_code; ?>_start_date_month" class="month">
                     <?php foreach($this->getMonths() as $k => $v): ?>
                        <option value="<?php print $k; ?>"><?php print $v; ?></option>
                     <?php endforeach; ?>
                </select>
                </div>
                <div class="v-fix">
                    <select name="payment[securetrading_stpp_start_date_year]" id="<?php print $_code; ?>_start_date_year" class="year">
                        <?php foreach($this->getStartYears() as $year): ?>
                            <option value="<?php print $year; ?>"><?php print $year; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </li>
        <?php endif; ?>
        <li>
            <label for="<?php print $_code; ?>_expiry_date_month" class="required">
                <?php print $this->getCardExpiryDateLabel(); ?>
                <em>*</em>
            </label>
            <div class="input-box">
                <div class="v-fix">
                    <select name="payment[securetrading_stpp_expiry_date_month]" id="<?php print $_code; ?>_expiry_date_month" class="month required-entry">
                         <?php foreach($this->getMonths() as $k => $v): ?>
                            <option value="<?php print $k; ?>"><?php print $v; ?></option>
                         <?php endforeach; ?>
                    </select>
                </div>
                <div class="v-fix">
                    <select name="payment[securetrading_stpp_expiry_date_year]" id="<?php print $_code; ?>_expiry_date_year" class="year required-entry">
                        <?php foreach($this->getExpiryYears() as $year): ?>
                            <option value="<?php print $year; ?>"><?php print $year; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            </div>
        </li>
        <li>
            <label for="<?php print $_code; ?>_security_code" class="required">
                <?php print $this->getCardSecurityCodeLabel(); ?>
                <em>*</em>
            </label>
            <div class="input-box">
                <input type="text" name="payment[securetrading_stpp_security_code]" id="<?php print $_code; ?>_security_code" class="required-entry" maxlength="4" />
                <?php //print $this->getCardSecurityCodeDescription(); ?>
            </div>
		</li>
		<?php if ($this->canShowIssueNumber()): ?>
		<li>
            <label for="<?php print $_code; ?>_issue_number">
                <?php print $this->getCardIssueNumberLabel(); ?>
            </label>
            <div class="input-box">
                <input type="text" name="payment[securetrading_stpp_issue_number]" id="<?php print $_code; ?>_issue_number" />
                <?php //print $this->getCardIssueNumberDescription(); ?>
            </div>
        </li>
        <?php endif; ?>
    </ul>
</fieldset>